name: client
description: EduTracky client application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.1
  camera: ^0.11.0+2
  flutter_riverpod: ^2.5.1
  go_router: ^14.6.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fl_chart: ^0.70.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - .env