name: Deploy to Firebase and Google Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'

      - name: Build Flutter web app
        working-directory: ./client
        run: |
          flutter --version
          flutter pub get
          flutter build web

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Firebase
        if: github.ref == 'refs/heads/main'
        run: |
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project ${{ secrets.GCP_PROJECT_ID }} --non-interactive
