name: Deploy to Firebase and Google Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Flutterのインストール
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      # Flutterの依存関係をキャッシュ
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      # 環境変数ファイルの作成
      - name: Create .env file
        run: |
          cd client
          touch .env
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> .env

      # Flutter Webのビルド
      - name: Build Flutter Web
        run: |
          cd client
          flutter pub get
          flutter build web

      # Node.jsのセットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Firebase CLIのインストール
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Google Cloud認証
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Google Cloud CLIのセットアップ
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      # Cloud Functionsのデプロイ
      - name: Deploy Cloud Functions
        run: |
          cd functions
          npm ci
          npm run build
          firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}" --project ${{ secrets.GCP_PROJECT_ID }}

      # Firebaseホスティングのデプロイ
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}" --project ${{ secrets.GCP_PROJECT_ID }}

      # Firestore rulesのデプロイ
      - name: Deploy Firestore Rules
        run: |
          firebase deploy --only firestore --token "${{ secrets.FIREBASE_TOKEN }}" --project ${{ secrets.GCP_PROJECT_ID }}

      # Storage rulesのデプロイ
      - name: Deploy Storage Rules
        run: |
          firebase deploy --only storage --token "${{ secrets.FIREBASE_TOKEN }}" --project ${{ secrets.GCP_PROJECT_ID }}
