name: Deploy to Firebase and Google Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Flutterのインストール
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'

      # Flutter設定とWebビルド
      - name: Build Web
        run: |
          cd client
          flutter config --no-analytics
          flutter pub get
          flutter build web
          cd ..

      # Node.jsのセットアップ
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Firebase CLIのインストール
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Google Cloud認証
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Google Cloud CLIのセットアップ
      - uses: google-github-actions/setup-gcloud@v2

      # Cloud Functionsのデプロイ
      - name: Deploy Cloud Functions
        if: github.ref == 'refs/heads/main'
        run: |
          cd functions
          npm ci
          npm run build
          firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}" --project ${{ secrets.GCP_PROJECT_ID }}

      # Firebaseホスティングのデプロイ
      - name: Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main'
        run: |
          firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}" --project ${{ secrets.GCP_PROJECT_ID }}

      # Firestore rulesのデプロイ
      - name: Deploy Firestore Rules
        if: github.ref == 'refs/heads/main'
        run: |
          firebase deploy --only firestore --token "${{ secrets.FIREBASE_TOKEN }}" --project ${{ secrets.GCP_PROJECT_ID }}

      # Storage rulesのデプロイ
      - name: Deploy Storage Rules
        if: github.ref == 'refs/heads/main'
        run: |
          firebase deploy --only storage --token "${{ secrets.FIREBASE_TOKEN }}" --project ${{ secrets.GCP_PROJECT_ID }}
